name: DevSecOps Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep_safety:
    name: SAST (Semgrep) + SCA (Safety)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install semgrep safety

      - name: Run Semgrep (SAST)
        run: |
          semgrep --config auto --json --output semgrep_report.json .

      - name: Run Safety (SCA)
        run: |
          safety check --file=requirements.txt --full-report --json > safety_report.json || true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: devsecops-reports
          path: |
            semgrep_report.json
            safety_report.json
